services:
  sas-restful-api:
    image: skyexit/sas-restful-api:v1.2.1-RELEASE
    depends_on:
      - db
    ports:
      - "5261:5260"
    restart: always
    networks:
      network1:
        ipv4_address: 172.20.0.2
  db:
    image: mysql:5.7
    restart: always
    networks:
      network1:
        ipv4_address: 172.20.0.3
    environment:
      MYSQL_DATABASE: 'database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'laurin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

networks:
  network1:
    name: sas-network
    external: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
